Check if gdlint installed and stop echo files

diff --git a/.github/workflows/gdlint-on-push.yml b/.github/workflows/gdlint-on-push.yml
--- a/.github/workflows/gdlint-on-push.yml
+++ b/.github/workflows/gdlint-on-push.yml
@@ -62,6 +62,11 @@ jobs:
         id: lint
         if: steps.changed-files.outputs.any_changed == 'true'
         run: |
+          # Ensure gdlint is available
+          if ! command -v gdlint &> /dev/null; then
+            echo "gdlint could not be found, please install gdtoolkit first."
+            exit 1
+          fi
           # Read the file list into an array robustly
           # files_array=(${{ steps.changed-files.outputs.all_changed_files }})
           changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
@@ -77,7 +82,7 @@ jobs:
 
           # Run gdlint with all files as arguments
           echo "Running gdlint on changed files:"
-          echo "$quoted_files"
+          # echo "$quoted_files"
           
           lint_output=$(eval gdlint $quoted_files 2>&1)
           exit_code=$?
